export function gatePage(url: string, key: string): string {
  const cfg = JSON.stringify({ url, key }).replace(/</g, '\\u003c');
  return `<!doctype html><html lang="uk"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GREATNESS - Сайт тимчасово закритий</title>
<style>*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;color:#f4f6fa;background:radial-gradient(ellipse at top,#153152,#080d17 65%);font:17px/1.5 system-ui,sans-serif}.card{width:min(100%,460px);padding:36px;border:1px solid #ffffff20;border-radius:24px;background:#101a2c;box-shadow:0 24px 70px #0005}.brand{color:#ffd166;letter-spacing:2px;font-weight:800}h1{font-size:30px;line-height:1.2}p{color:#b3bfd1}label{display:block;margin:18px 0 6px}input,button{width:100%;padding:14px;border-radius:12px;font:inherit}input{color:white;background:#091221;border:1px solid #526178}button{margin-top:18px;border:0;color:#101a2c;background:#ffd166;font-weight:700;cursor:pointer}.google{background:#263954;color:white}button:disabled{opacity:.5;cursor:wait}#message{min-height:26px;color:#ffb8a8}details{margin-top:24px}summary{cursor:pointer;color:#ffd166}</style>
<main class="card"><div class="brand">GREATNESS</div><h1>Сайт тимчасово закритий</h1><p>Доступ до сайту обмежено.</p><details open><summary>Вхід власника</summary><form id="login"><label for="email">Email</label><input id="email" type="email" autocomplete="username" required><label for="password">Пароль</label><input id="password" type="password" autocomplete="current-password" required><button id="submit">Увійти</button></form><button class="google" id="google" type="button">Увійти через Google</button></details><p id="message" role="status" aria-live="polite"></p></main>
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script><script>
const cfg=${cfg};const message=document.getElementById('message');let client;
const show=t=>message.textContent=t;
async function unlock(session){if(!session?.access_token)return;const r=await fetch('/owner-access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:session.access_token})});const b=await r.json();if(r.ok)location.replace('/');else{show(b.error||'Вхід недоступний.');await client.auth.signOut();}}
async function init(){if(!cfg.url||!cfg.key||!window.supabase){show('Вхід тимчасово недоступний.');return;}client=window.supabase.createClient(cfg.url,cfg.key);const {data,error}=await client.auth.getSession();if(error)show('Не вдалося відновити вхід.');else if(data.session)await unlock(data.session);}
document.getElementById('login').addEventListener('submit',async e=>{e.preventDefault();if(!client)return;const btn=document.getElementById('submit');btn.disabled=true;show('Перевіряємо вхід…');try{const {data,error}=await client.auth.signInWithPassword({email:document.getElementById('email').value.trim(),password:document.getElementById('password').value});document.getElementById('password').value='';if(error)show('Не вдалося увійти. Перевір email та пароль.');else await unlock(data.session);}catch{show('Не вдалося підключитися. Спробуй ще раз.');}finally{btn.disabled=false;}});
document.getElementById('google').addEventListener('click',async()=>{if(!client)return;const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/owner-access'}});if(error)show('Вхід через Google недоступний.');});init().catch(()=>show('Не вдалося підключитися. Спробуй ще раз.'));
</script></html>`;
}
